### ISSUE TITLE
Regression introduced in msys2-runtime-3.3.6-1 when executing cmd /c 

### ISSUE THREAD

**Issue by pbatard** [msys2/Cygwin#108]
There has been a regression in msys2-runtime when it comes to invoking `cmd.exe`

Here is the old expected behaviour with msys2-runtime-3.3.5-3 or earlier:
```
pete@good_msys MINGW32 ~
$ uname -a
MINGW32_NT-10.0-22621 good_msys 3.3.5-341.x86_64 2022-07-04 21:33 UTC x86_64 Msys

pete@good_msys MINGW32 ~
$ cmd.exe /c 'echo BLAH'
BLAH
```

And this is what happens when upgrading to msys2-runtime-3.3.6-1 or later:
```
pete@bad_msys MINGW32 ~
$ uname -a
MINGW32_NT-10.0-22621 bad_msys 3.3.6-341.x86_64 2022-09-20 22:07 UTC x86_64 Msys

pete@bad_msys MINGW32 ~
$ cmd.exe /c 'echo BLAH'
bash: /c/Windows/System32/cmd.exe: Bad address
```

This issue has been confirmed by other people (on the Discord channel)  and whereas, for the simple example above, one workaround has been found, which consists of doubling the '/' (`cmd.exe //c 'echo BLAH'`), such a workaround does not appear to be effective with more complex command invocations, [such as one I am using in a bash script where `signtool.exe` must be invoked in order to digitally sing a PowerShell script](https://github.com/pbatard/Fido/blob/master/sign.sh#L24). In this case, when using `//`,  the `Bad address` error  becomes `'\"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool\"' is not recognized as an internal or external command, operable program or batch file`.

I am therefore opening this issue to ask the msys2-runtime developers to investigate the changes that occurred between 3.3.5-3 and 3.3.6-1, in order to fix this regression, so that invoking a complex command such as `cmd.exe /c '"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool" sign /v /sha1 3dbc3a2a0e9ce8803b422cfdbc60acd33164965d /fd SHA256 /tr http://sha256timestamp.ws.symantec.com/sha256/timestamp /td SHA256 Fido.ps1'` from bash will work as it did before.

**Comment by dscho** [comment]
I could reproduce and bisected this to msys2/msys2-runtime@2b4f986e499f040966be72516dae5b01ef721d24, i.e. a patch that came in via Cygwin. Reverting it fixes the `Bad address` problem.

On a hunch, I applied this patch instead of reverting that commit, and it _also_ fixed the problem:

```diff
diff --git a/winsup/cygwin/spawn.cc b/winsup/cygwin/spawn.cc
index bc9dc5af37..6b1d009b77 100644
--- a/winsup/cygwin/spawn.cc
+++ b/winsup/cygwin/spawn.cc
@@ -209,7 +209,7 @@ is_console_app (WCHAR *filename)
   char *p = (char *) memmem (buf, n, "PE\0\0", 4);
   if (p && p + id_offset < buf + n)
     return p[id_offset] == '\003'; /* 02: GUI, 03: console */
-  else
+  else if (filename)
     {
       wchar_t *e = wcsrchr (filename, L'.');
       if (e && (wcscasecmp (e, L".bat") == 0 || wcscasecmp (e, L".cmd") == 0))
```

That `filename` can be `NULL` if the command line is `cmd.exe /c [...]`.

**Comment by dscho** [comment]
@pbatard I am hopeful that https://github.com/msys2/msys2-runtime/actions/runs/3300631782#artifacts will build all right and then publish a `.zip`. Would you mind downloading that `.zip`, extracting the `msys-2.0.dll` and replace yours (in `/usr/bin/msys-2.0.dll`, obviously no MSYS2 programs can run while you do that) and then test whether this fixes the problem on your side, too?

**Comment by pbatard** [comment]
I can confirm that `msys-2.0.dll` from the [3300631782#artifacts](https://github.com/msys2/msys2-runtime/actions/runs/3300631782#artifacts) fixes the issue.

Thanks a lot for the fast turnaround on this!

**Comment by dscho** [comment]
> I can confirm that `msys-2.0.dll` from the [3300631782#artifacts](https://github.com/msys2/msys2-runtime/actions/runs/3300631782#artifacts) fixes the issue.

@pbatard thank you for testing!

Sadly, my patch was rejected and summarily replaced with a different patch. I hate to have to ask you to test another build artifact, but if you would be so kind as to test the `msys-2.0.dll` from https://github.com/msys2/msys2-runtime/actions/runs/3308315068#artifacts?

**Comment by pbatard** [comment]
No worries about the extra testing. I just tested the `msys-2.0.dll` from the [3308315068#artifacts](https://github.com/msys2/msys2-runtime/actions/runs/3308315068#artifacts) and can confirm that this works fine too.
