### ISSUE TITLE
not output to stdout console after use vector

### ISSUE THREAD

**Issue by gaoxinge** [msys2/Cygwin#111]
I use `pacman -Syu` to update `gcc` and `g++` yesterday:  

```
(Rev4, Built by MSYS2 project) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But when I run cpp code below

```cpp
#include <iostream>
#include <vector>

int main() {
    std::cout << "=====" << std::endl;
    std::vector<float> a(10);  // add vector
    return 0;
}
```

the program will not output `=====` in the stdout console.

**Comment by Biswa96** [comment]
I can not reproduce the issue. Here is the screenshot in my setup with the output showing in terminal window.

![image](https://user-images.githubusercontent.com/31443074/198496581-e45441cd-d45f-47fa-825a-be0d6d0de669.png)

**Comment by gaoxinge** [comment]
@Biswa96 Oh yes. This only happens when I use the windows git terminal, not windows msys2 terminal. And fix after I update windows git terminal Thx.
