### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by Vuniverse0** [msys2/Cygwin#128]
Where I can find documentation/tutorial/instruction for building msys2-runtime. I want to try write some code, compile it and use dll that I will get in msys2 that installed on my computer.

Thanks.

**Comment by Biswa96** [comment]
Do you want to compile native Windows binary with native Windows API? If yes you do not need msys2-runtime for you program.

**Comment by Vuniverse0** [comment]
I need to replace internal msys2-runtime function in msys2-runtime to benchmark, test and debug.

**Comment by Biswa96** [comment]
Alright. The build procedure is fairly straight. Just `./configure` and `make`. The verbose build procedure can be found here https://github.com/msys2/MSYS2-packages/blob/master/msys2-runtime/PKGBUILD

If you use the default branch in this repository it does not required any patching.
If you use the cygwin/master branch you need the patches from here https://github.com/msys2/MSYS2-packages/tree/master/msys2-runtime

**Comment by Vuniverse0** [comment]
Thank you. And about, which packages I should install?

**Comment by Biswa96** [comment]
You have to install all the packages mentioned in makedepends list in msys2-runtime [PKGBUILD][1] file.

[1]: https://github.com/msys2/MSYS2-packages/blob/master/msys2-runtime/PKGBUILD

**Comment by Vuniverse0** [comment]
Thanks
