### ISSUE TITLE
msys-2.0.dll

### ISSUE THREAD

**Issue by Vuniverse0** [msys2/Cygwin#129]
I was run ./config with prefix, and make install. I founded in prefix dir libc.a, libm.a, libg.a, but I need msys-2.0.dll. Where\How I must get it? 

Thanks.

**Comment by Biswa96** [comment]
You can use `find` command to find the dll. Also see the `package_msys2-runtime()` in [msys2-runtime PKGBILD](https://github.com/msys2/MSYS2-packages/blob/master/msys2-runtime/PKGBUILD) file.

BTW, if you have general questions you can join Discord or Gitter or IRC. Links can be found in the footer of this page https://www.msys2.org/

**Comment by Vuniverse0** [comment]
I mean that in prefix dir are only headers and static libs, why I wasn`t get dll files?

**Comment by Biswa96** [comment]
It's hard to speculate any reason with less info. I'd suggest to follow the PKGBUILD carefully. Every step is important.

**Comment by Vuniverse0** [comment]
So, https://github.com/msys2/msys2-runtime/blob/msys2-3.4.3/README isn`t relevant?

**Comment by Biswa96** [comment]
It's relevant but it may not explain all the steps for first time user.

**Comment by Vuniverse0** [comment]
There is big list of patches in PKGBULD, are them applied or I must apply it myself?

**Comment by Biswa96** [comment]
If you use the default branch in this repository it does not required any patching.

**Comment by Vuniverse0** [comment]
thanks

**Comment by Vuniverse0** [comment]
I get it by run ./autogen in winsup. 

Thanks.
