### ISSUE TITLE
 sigfe.s: No such file or directory.

### ISSUE THREAD

**Issue by hakonhagland** [msys2/Cygwin#13]
**OS**: Windows 10.

**MSYS2 configuration**: 
I installed MSYS2 from https://www.msys2.org/, then opened a MSYS2 terminal window and ran

```
> pacman -Syu
> pacman -S base-devel gcc vim cmake git libcrypt-devel libreadline tree
```
Now I am debugging a C program from the MSYS2 terminal window using `gdb`. The C program calls `dlopen()` and when I step into the call with `gdb` I get:

```
(gdb) s
 _sigfe_dlopen () at sigfe.s:2652
2652    sigfe.s: No such file or directory.
(gdb) info source
Current source file is sigfe.s
Compilation directory is /msysdev/msys2-runtime/src/build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin
Source language is asm.
Producer is GNU AS 2.34.
Compiled with DWARF 2 debugging format.
Does not include preprocessor macro info.
```

Note that it says compilation directory is `/msysdev/msys2-runtime/src/build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin` but when I try to enter the directory from the MSYS2 terminal:

```
> ls /msysdev
ls: cannot access '/msysdev': No such file or directory
```
Any idea how I can get hold of the source files so I can debug this call to `dlopen()` ?

**Comment by dscho** [comment]
You will need to check out the source code somewhere, make sure that it is pointing to the correct commit, and then you will have to [specify the source directory](https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html).

However, `sigfe.s` is not part of the source code of the MSYS2 runtime. It is [generated at build time](https://stackoverflow.com/questions/44770147/gdb-in-cygwin-is-missing-sigfe-s).

In any case, seeing the source code for `sigfe` is probably not going to help you. You can read https://github.com/msys2/msys2-runtime/blob/msys2-3_1_7-release/winsup/cygwin/how-signals-work.txt for more information on this.

What line 2652 looks over here is this:

```
        leaq    dlopen(%rip),%r10
```

It is part of the `_sigfe_dlopen` wrapper:

```
        .extern dlopen
        .global _sigfe_dlopen
        .seh_proc _sigfe_dlopen
_sigfe_dlopen:
        leaq    dlopen(%rip),%r10
        pushq   %r10
        .seh_pushreg %r10
        .seh_endprologue
        jmp     _sigfe
        .seh_endproc
```

The `_sigfe` code looks like this:

```
        .seh_proc _sigfe
_sigfe:                                         # stack is aligned on entry!
        .seh_endprologue
        movq    %gs:8,%r10                      # location of bottom of stack
1:      movl    $1,%r11d                        # potential lock value
        xchgl   %r11d,-7092(%r10)       # see if we can grab it
        movl    %r11d,-7096(%r10)       # flag if we are waiting for lock
        testl   %r11d,%r11d                     # it will be zero
        jz      2f                              #  if so
        pause
        jmp     1b                              # loop
2:      movq    $8,%rax                 # have the lock, now increment the
        xaddq   %rax,-7088(%r10)        #  stack pointer and get pointer
        leaq    _sigbe(%rip),%r11               # new place to return to
        xchgq   %r11,8(%rsp)                    # exchange with real return value
        movq    %r11,(%rax)                     # store real return value on alt stack
        incl    -7100(%r10)
        decl    -7092(%r10)             # remove lock
        popq    %rax                            # pop real function address from stack
        jmp     *%rax                           # and jmp to it
        .seh_endproc
```

So you see that this really is just a wrapper, and it will eventually jump to `dlopen()`'s actual code.

After checking out the source code (you could even create the directory `/msysdev/msys2-runtime/src/` and run `git clone https://github.com/msys2/msys2-runtime` in there, to avoid having to specify the source path), you should be able to set a break point on the `dlopen` function and see its source code.
