### ISSUE TITLE
query while building winsup

### ISSUE THREAD

**Issue by goyalyashpal** [msys2/Cygwin#137]
### Summary
- I am trying to build the artifacts similar to what's done in the run-jobs for the "sync with cygwin" pulls 
- why? as they are expired on the concerned pull: [#96]
- It does `checking for i686-w64-mingw32-gcc... no` 
- i want to ask is there a way to successfully build without this `i686-gcc` aka `gcc:i` too??

### Steps took
* download the <tt>winsup</tt> and thereafter <tt>newlib</tt> [directories]
* run following commands - got stuck on i686-gcc required...
* i didn't do anything after that - as removing that "check" would be like sneaking. the check exists because it would be used later right? so, use of `i686-gcc` would require removing at other places too - which i am unaware of.

```console
$ cd winsup && ./autogen.sh
$ ./configure
```

but it fails with error:

```log
checking for i686-w64-mingw32-gcc... no
configure: error: no acceptable mingw32 gcc found in $PATH
```

----
### References:

Above error (from <tt>[less] ./autogen.sh</tt> and `aclocal --help`):
* `configure.ac` 
https://github.com/msys2/msys2-runtime/blob/9310e06e39164a10de69af7d4e7fef8cc5240749/winsup/configure.ac#L99-L100

Run commands: 
* [workflow-file]
https://github.com/msys2/msys2-runtime/blob/108a4aca5610d4e4d74caaa65fce3342e36fd10e/.github/workflows/build.yaml#L21-L25 
* winsup/README
https://github.com/msys2/msys2-runtime/blob/108a4aca5610d4e4d74caaa65fce3342e36fd10e/winsup/README#L8 

[less]: https://askubuntu.com/a/1191866/1613150
[directories]: https://github.com/msys2/msys2-runtime/tree/9310e06e39164a10de69af7d4e7fef8cc5240749
[#96]: https://github.com/msys2/msys2-runtime/pull/96#event-6932555159
[workflow-file]: https://github.com/msys2/msys2-runtime/actions/runs/2614940483/workflow

**Comment by Biswa96** [comment]
Install the required packages as mentioned in [msys2-runtime PKGBUILD](https://github.com/msys2/MSYS2-packages/blob/master/msys2-runtime/PKGBUILD).

**Comment by goyalyashpal** [comment]
> Install the required packages

yep, as per the [workflow-file] and quoted below, I did check those (after removing `-devel` suffix), and here's what i got:




https://github.com/msys2/msys2-runtime/blob/108a4aca5610d4e4d74caaa65fce3342e36fd10e/.github/workflows/build.yaml#L18

### Console log:

<details><summary><tt>pacman -S</tt></summary>

```console
$ pacman -S msys2 base autotools cocom diffutils gcc gettext libiconv make mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib perl zlib xmlto docbook-xsl
error: target not found: msys2
warning: base-2022.06-1 is up to date -- reinstalling
warning: autotools-2022.01.16-2 is up to date -- reinstalling
warning: gettext-0.21-2 is up to date -- reinstalling
warning: libiconv-1.17-1 is up to date -- reinstalling
warning: docbook-xsl-1.79.2-3 is up to date -- reinstalling
```
</details>

<details><summary><tt>pacman -Q</tt></summary>

```console
$ pacman -Q msys2 base autotools cocom diffutils gcc gettext libiconv make mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib perl zlib xmlto docbook-xsl
error: package 'msys2' was not found
base 2022.06-1
autotools 2022.01.16-2
error: package 'cocom' was not found
diffutils 3.8-3
error: package 'gcc' was not found
gettext 0.21-2
libiconv 1.17-1
make 4.3-3
error: package 'mingw-w64-cross-crt' was not found
error: package 'mingw-w64-cross-gcc' was not found
error: package 'mingw-w64-cross-zlib' was not found
perl 5.32.1-2
zlib 1.2.12-2
xmlto 0.0.28-3
docbook-xsl 1.79.2-3
```

</details>

[workflow-file]: https://github.com/msys2/msys2-runtime/actions/runs/2614940483/workflow

**Comment by Biswa96** [comment]
> after removing -devel suffix

Did anyone tell you to remove the `-devel` suffix? Those are required packages to compiled stuff in msys2 environment.

Also learn the pacman commands first. The ` pacman -Q` command shows what packages are installed in the system. So, you clearly have not installed mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib etc. packages.

**Comment by goyalyashpal** [comment]
> Did anyone tell you to remove the `-devel` suffix?
> you clearly have not installed

yes, but i ran `pacman -S` before `pacman -Q` on the package name list and it didn't fetch any results regarding the packages which are not installed.

**Comment by Biswa96** [comment]
> ...it didn't fetch any results regarding the packages which are not installed.

Because it failed with this error: target not found: msys2. msys2 is not a package.

**Comment by goyalyashpal** [comment]
> Because it failed with this error: target not found: msys2. msys2 is not a package.

ohwww, ohkay. retrying then.

Roughly grouping them according to their purpose (as per the cygwin faq)
related: https://www.msys2.org/news/#2021-12-22-ongoing-cleanup-of-the-base-devel-package-group

```console
# Necessary build tools
pacman -S base-devel autotools diffutils make
pacman -S msys2-devel cocom gcc perl gettext-devel libiconv-devel zlib-devel 

# Building for 64-bit msys
pacman -S mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib 

# Building the documentation
pacman -S docbook-xsl xmlto 
```

or in single command:

```console
pacman -S base-devel autotools diffutils make msys2-devel cocom gcc perl gettext-devel libiconv-devel zlib-devel mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib docbook-xsl xmlto 
```

----

<details><summary><tt>pacman -Qu</tt></summary>

```console
$ pacman -Qu base-devel autotools diffutils make msys2-devel cocom gcc perl gettext-devel libiconv-devel zlib-devel mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib docbook-xsl xmlto
error: package 'base-devel' was not found
diffutils 3.8-3 -> 3.8-4
make 4.3-3 -> 4.4-1
error: package 'msys2-devel' was not found
error: package 'cocom' was not found
error: package 'gcc' was not found
perl 5.32.1-2 -> 5.36.0-1
error: package 'zlib-devel' was not found
error: package 'mingw-w64-cross-crt' was not found
error: package 'mingw-w64-cross-gcc' was not found
error: package 'mingw-w64-cross-zlib' was not found
xmlto 0.0.28-3 -> 0.0.28-4
```

</details>
<details><summary><tt>pacman -S</tt></summary>

```console
$ pacman -S base-devel autotools diffutils make msys2-devel cocom gcc perl gettext-devel libiconv-devel zlib-devel mingw-w64-cross-crt mingw-w64-cross-gcc mingw-w64-cross-zlib docbook-xsl xmlto
warning: autotools-2022.01.16-2 is up to date -- reinstalling
warning: gettext-devel-0.21-2 is up to date -- reinstalling
warning: libiconv-devel-1.17-1 is up to date -- reinstalling
warning: docbook-xsl-1.79.2-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (29) 
              ... MORE ...

Total Download Size:    143.31 MiB
Total Installed Size:  1150.10 MiB
Net Upgrade Size:      1074.99 MiB

:: Proceed with installation? [Y/n]
```
</details>

<details><summary>Packages (29)</summary>

```
binutils-2.40-1  gcc-libs-11.3.0-3  isl-0.25-2
              mingw-w64-cross-binutils-2.37-1
              mingw-w64-cross-headers-git-9.0.0.6158.1c773877-1
              mingw-w64-cross-windows-default-manifest-6.4-2
              mingw-w64-cross-winpthreads-git-9.0.0.6158.1c773877-1
              mpc-1.3.0-2  msys2-runtime-3.4.5-1  msys2-runtime-devel-3.4.5-1
              msys2-w32api-headers-10.0.0.r16.g49a56d453-1
              msys2-w32api-runtime-10.0.0.r16.g49a56d453-1
              windows-default-manifest-6.4-1  zlib-1.2.13-1
              autotools-2022.01.16-2  base-devel-2022.12-2  cocom-0.996-3
              diffutils-3.8-4  docbook-xsl-1.79.2-3  gcc-11.3.0-3
              gettext-devel-0.21-2  libiconv-devel-1.17-1  make-4.4-1
              mingw-w64-cross-crt-git-9.0.0.6158.1c773877-1
              mingw-w64-cross-gcc-10.2.0-2  mingw-w64-cross-zlib-1.2.11-1
              perl-5.36.0-1  xmlto-0.0.28-4  zlib-devel-1.2.13-1
```

</details>
