### ISSUE TITLE
I need help with my custom repl support

### ISSUE THREAD

**Issue by RickBarretto** [msys2/Cygwin#144]
Hello, sorry for the inconvenience!

> TLDR: Yes, I'd read about the problems that exists with Msys and other applications and I'm aware that is a "lottery". Even Python's REPL has problem with Msys. But in my case, is an application that I know the codebase (and I can change things there just to support it) and I wanting to fix it, asap.

First, I read about the problems and incompatibilities with some applications, but I know that some applications works very well with Msys's terminal, as Emacs and Nano.

My problem is on an application that I'm currently contributing, [Arturo](https://github.com/arturo-lang/arturo) created by @drkameleon . And I have a total of 4 issues with REPL while using Msys2 ([#arturo/1093](https://github.com/arturo-lang/arturo/issues/1093), [#arturo/1092](https://github.com/arturo-lang/arturo/issues/1092), [#arturo/1091](https://github.com/arturo-lang/arturo/issues/1091) and [#arturo/1090](https://github.com/arturo-lang/arturo/issues/1090)).

So, is there a way to make it work, as Nano does? Or is it a completely lottery? Or should I just recommend the users to run with `winpty`?

**Comment by sskras** [comment]
Might have something to do with the @mintty implementation too, ie: [mintty/mintty](https://github.com/mintty/mintty/)

**Comment by RickBarretto** [comment]
> Might have something to do with the @mintty implementation too, ie: [mintty/mintty](https://github.com/mintty/mintty/)

Hello, and thanks! 
I did some search on [mintty/mintty](https://github.com/mintty/mintty/) and I probably found what I was looking for: [Keycode's Documentation](https://github.com/mintty/mintty/wiki/Keycodes) and [CtrlSeq's Documentation](https://github.com/mintty/mintty/wiki/CtrlSeqs). Well, if I found some issues, I'll open in Mintty's repository to look for help.

Again, thanks for the reply! 🙂

**Comment by mintty** [comment]
This sounds like it might be an issue with a Windows application, not compiled for cygwin/MSYS.
Please report the MSYS version (`uname -a`) and whether ConPTY support is enabled (`echo $MSYS`).
Also, if you intend to report to mintty, please provide a reproducible test case, preferably without using exotic software. A mintty screen log can be created with option `-l`.

**Comment by RickBarretto** [comment]
> not compiled for cygwin/MSYS

Yes, you're right. I'll have a look on it.

```shell
$ uname -a
MSYS_NT-10.0-14393 DESKTOP-ME96FPJ 3.4.6.x86_64 2023-02-15 18:03 UTC x86_64 Msys
$ echo $MSYS

```
Yes, `echo $MSYS` returns an empty line to me.

> Also, if you intend to report to mintty, please provide a reproducible test case, preferably without using exotic software.

All right! 😉

**Comment by RickBarretto** [comment]
I have a question.
Should `echo $MSYS` return nothing to me?

**Comment by Biswa96** [comment]
> Should echo $MSYS return nothing to me?

MSYS and CYGWIN environment variables are used to configure some properties. So, if you have not configure any settings it should return nothing.

> Or should I just recommend the users to run with winpty?

In those arturo project's issue, it seems that the terminal in-use is not mintty. So, that kind of issues are expected. So, winpty may be a proper workaround.
