### ISSUE TITLE
resolve windows environment variables for paths

### ISSUE THREAD

**Issue by goyalyashpal** [msys2/Cygwin#146]
will it make sense to resolve the windows environment variables (enclosed in %) for paths in the msys2 shell?

this will make the windows environment variables like `%localappdata%` and others to work.
these are supported in windows stuff like windows explorer, `cmd`  (but surprisingly, not in `powershell`)

i was thinking of using like this: 

```console
$ cd %localappdata%
```

```console
$ mv %userprofile%/some-file /d/my-dir
```

currently these variables are not resolved and error is shown: `bash: cd: %localappdata%: No such file or directory`

**Comment by Biswa96** [comment]
> will it make sense to resolve the windows environment variables (enclosed in %) for paths in the msys2 shell?

No, it's a convention to use `%` for environment variables in Windows or DOS like OS. Whereas `$` is used for unix-like environment.

In case of bash, `%` is used for other purposes, like string format specifier, pattern matching, arithmetic operation etc. More info can be found in bash man page https://www.man7.org/linux/man-pages/man1/bash.1.html.

> this will make the windows environment variables like %localappdata% and others to work.

If you want to use cmd like syntax you can use msys2 by adding the installation directories in %PATH% env. variable in cmd or powershell. But some tools may not work as expected.

**Comment by goyalyashpal** [comment]
> cmd like syntax [with msys2 tools], you can use msys2 by adding the installation directories in %PATH% env. variable in cmd or powershell

ahw, really nice. yep, `ls "%localappdata%"` worked from `cmd` (not from `powershell` - this might be due to old powershell instance, but couldn't figure out its version lol)

also, `powershell /?` doesn't work from `bash` - so, its interesting that the environment interacts and modifies the command invocation. i had only read this in msys2 documentation, but experiencing it this drastically for the first time.

kinda amazing.

also, i was thinking of adding these windows environment variables in the `$` format in one of my msys config file, then doing something like `ls "${localappdata}"`

**Comment by Biswa96** [comment]
> ls "%localappdata%" worked from cmd

It works from msys2 bash also. See the following output.

```
$ echo $LOCALAPPDATA
C:\Users\x\AppData\Local

$ ls -lash $LOCALAPPDATA | wc -l
42
```

**Comment by goyalyashpal** [comment]
> [with the dollar instead of percents] It works from msys2 bash also. See the following output.

brilliant :) super neat, one more reason to love msys2 from my side

reminder to self, yes, it has to be case sensitive
