### ISSUE TITLE
Sometimes can't fork sub process.

### ISSUE THREAD

**Issue by Git-Learn1** [msys2/Cygwin#165]
This is my first time installing MSYS2. When I execute commands such as `pacman -Syu` (almost any command), the console will print information prompts like them:
> 0 [main] bash (19340) child_copy: cygheap read copy failed, 0x0..0x800029A98, done 0, windows pid 19340, Win32 error 299
 0 [main] bash 1199 dofork: child -1 - forked process 19340 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
./configure: fork: retry: Resource temporarily unavailable
 0 [main] grep (16216) child_copy: cygheap read copy failed, 0x0..0x80002A538, done 0, windows pid 16216, Win32 error 299

These are the errors that occurred during the execution of `./configure` (any project)
Sometimes there won't be any error.
I'm using Windows 11 build 25905. I think it is a problem of the new kernel written by Rust.
I also turned off "Enforce ASLR"

**Comment by mati865** [comment]
> I think it is a problem of the new kernel written by Rust.

Only small part of the kernel has been rewritten so it might be this change or something entirely different. New insider builds fairly often require changes to Cygwin's code, could you test with Cygwin and report problem there if it reproduces?

**Comment by Git-Learn1** [comment]
Oh, I almost forgot about this. I have already tested both the stable and test versions. The stable version has the same issue, but in test version, This issue has been fixed。
So I will wait for the test version to be pushed to the stable version, and MSYS2's core update. Now I'm going to close this issue.

**Comment by Git-Learn1** [comment]
[https://cygwin.com/cgit/newlib-cygwin/commit/?id=c431f6b7fe11edc1e1cb1a8aec1205ca1713402b](url)
[https://cygwin.com/cgit/newlib-cygwin/commit/?id=89e80d414b9d4ec71c6d43503704f7b3da3a2407](url)
[https://cygwin.com/cgit/newlib-cygwin/commit/?id=a02144808c5bc4e9753bfeabf06313c6413e1cd3](url)
Maybe these commits fix the problem.
