### ISSUE TITLE
Path conversions in cpp macros are broken

### ISSUE THREAD

**Issue by hyc** [msys2/Cygwin#174]
If I run a command like 
  gcc -DMYPATH='"/tmp:/bin"' -c xx.c

the path that cpp actually sees is 
  "C:\msys64\tmp;C:\msys64\usr\bin"

but this isn't a valid C string, the compiler thinks \m \t \u and \b are C escape sequences and they're not all valid.

Simplest fix would be to convert to mixed mode, like "C:/msys64/tmp;C:/msys64/usr/bin" instead. Possibly with an env var setting to select which mode to autoconvert to. Another option would be an env var to force conversions to use double-backslashes or somesuch, if staying in pure DOS mode.

**Comment by dscho** [comment]
You would need to use `MSYS2_ARG_CONV_EXCL` (see https://www.msys2.org/docs/filesystem-paths/#process-arguments for details).

However, I must ask: if you are trying to hard-code Unix-style paths in the executable, do you really want to compile with a MINGW compiler? If you'd use an MSYS compiler, the path conversion would not happen, and everything would work as intended.

**Comment by hyc** [comment]
Thanks, I was looking for exactly that but didn't find it before.

In this case, the compiled-in string is just a placeholder and gets overridden by runtime config anyway, so its particular value doesn't really matter, but the autoconf scripts will give it a default and it's just a hassle that the default turns into illegal escape chars.
