### ISSUE TITLE
isdigit macro in <ctype.h> triggers -Wchar-subscripts when expanded in user code

### ISSUE THREAD

**Issue by hexian000** [msys2/Cygwin#186]
https://github.com/msys2/msys2-runtime/blob/76fd7eae5a9c9350e1a78937d2f85f9c881f3c92/newlib/libc/include/ctype.h#L90

Macro argument __c should always be casted to int before use.

I think it should be:

```C
#define __ctype_lookup(__c) ((__CTYPE_PTR+sizeof(""[(int)(__c)]))[(int)(__c)])
```

**Comment by hexian000** [comment]
Sorry, my mistake.

**Comment by Biswa96** [comment]
Could you kindly provide information about the mistake that was made? It would greatly assist us to have this knowledge.

**Comment by hexian000** [comment]
> Could you kindly provide information about the mistake that was made? It would greatly assist us to have this knowledge.

I didn't read the comments above the quoted line carefully. This useful warning is triggered intentionally only by MSYS. (but not in normal Linux gcc toolchains, which is why I mistakenly thought it was a msys issue)

**Comment by dscho** [comment]
This error usually means that `isdigit()` is called with `char` parameters, i.e. _signed_ 8-bit values. If you cast those to `(int)`, you end up with 32-bit values in the range -128...127, which is really, really wrong here. What should be done is to cast the `char` to `(unsigned char)`. But that requires validating that the original parameter is actually a `char`.
