### ISSUE TITLE
I suggest to add this x86_64-msys target to gcc itself

### ISSUE THREAD

**Issue by trcrsired** [msys2/Cygwin#188]
Adding patch is annoying and it is very hard to do canadian compilation.

**Comment by dscho** [comment]
Hmm. I _think_ I understand where you are coming from. Does Cygwin do that already? If not, why not?

**Comment by lazka** [comment]
We are trying to get rid of x86_64-msys in the long term and use x86_64-cygwin everywhere: https://github.com/msys2/MSYS2-packages/issues/3012

Would that help you?

**Comment by dscho** [comment]
I take that silence as an affirmative answer. I'd be fine with closing this. What do you think @lazka?
