### ISSUE TITLE
ls/stat on OneDrive causes download of files

### ISSUE THREAD

**Issue by mwisnicki** [msys2/Cygwin#206]
If I invoke ls or anything else that does stat inside OneDrive folder it will trigger download of all files.

OneDrive uses [placeholder files](https://learn.microsoft.com/en-us/windows/win32/w8cookbook/placeholder-files) to represent remote files.

I'm guessing reading file content in stat is to support detection of actually executable files as in [here](https://github.com/msys2/msys2-runtime/blob/msys2-3.4.10/winsup/cygwin/fhandler/disk_file.cc#L548)?

I think this should be disabled on non-hydrated placeholder files.

**Comment by dscho** [comment]
Sadly, this is within the l design of Cygwin/MSYS2: to determine whether a file is a script, the runtime needs to read the first few bytes from the file. And the way OneDrive seems to operate, it anticipates from that read that the entire file is needed locally.

**Comment by mwisnicki** [comment]
I would be happy to have non-hydrated placeholder files to be non-executable.

**Comment by mwisnicki** [comment]
Another approach that could help - skip checking files with extensions known to be non-executable such as jpg (or just any extensions that is not known to be executable).

**Comment by dscho** [comment]
> I would be happy to have non-hydrated placeholder files to be non-executable.

I fear that I have not managed to make myself plain: This behavior is a design decision of Cygwin. If you want to convince anybody to change that behavior, you will need to take it up with the Cygwin maintainers (see https://cygwin.com/problems.html for details).

**Comment by mwisnicki** [comment]
Thanks. I thought MSYS forked off Cygwin long ago. Didn't realize it's still tracking upstream.

**Comment by mwisnicki** [comment]
Moved to https://sourceware.org/pipermail/cygwin/2024-March/255613.html

**Comment by dscho** [comment]
Thanks.
