### ISSUE TITLE
Mount C:/msys64/home as /home with acl support

### ISSUE THREAD

**Issue by ArchGuyWu** [msys2/Cygwin#224]
chmod can't work under /home due to noacl option set for C:/msys64 (mount as /).

**Comment by sskras** [comment]
I think it's a dup of https://github.com/msys2/MSYS2-packages/issues/2612

**Comment by ArchGuyWu** [comment]
> I think it's a dup of [msys2/MSYS2-packages#2612](https://github.com/msys2/MSYS2-packages/issues/2612)

No, I removed noacl for /c and successfully created a directory under it with permissions set to 0700. However, when moving the directory to /home, the permissions were lost, and moving it back to /c restored them.

**Comment by ArchGuyWu** [comment]
![2024-08-07_22-51](https://github.com/user-attachments/assets/5be43f0c-d9c7-4495-bcdc-c967d1060899)

**Comment by sskras** [comment]
> No, I removed noacl for /c and successfully created a directory under it with permissions set to 0700. However, when moving the directory to /home, the permissions were lost, and moving it back to /c restored them.

Thanks for clarifying. Have you tried mounting /home with `acl` too? Eg:
```sh
saukrs@DESKTOP-O7JE7JE MSYS ~
$ mount C:/msys64/home /home -o acl

saukrs@DESKTOP-O7JE7JE MSYS ~
$ mount | grep /home
C:/msys64/home on /home type ntfs (binary,user)

```

**Comment by sskras** [comment]
Thanks for clarifying. Have you tried remounting /home separately? Eg:
```sh
saukrs@DESKTOP-O7JE7JE MSYS ~
$ mount C:/msys64/home /home

saukrs@DESKTOP-O7JE7JE MSYS ~
$ mount | grep /home
C:/msys64/home on /home type ntfs (binary,user)

```

PS. I removed my previous (misleading) comment.

**Comment by ArchGuyWu** [comment]
> Thanks for clarifying. Have you tried remounting /home separately? Eg:
> 
> ```shell
> saukrs@DESKTOP-O7JE7JE MSYS ~
> $ mount C:/msys64/home /home
> 
> saukrs@DESKTOP-O7JE7JE MSYS ~
> $ mount | grep /home
> C:/msys64/home on /home type ntfs (binary,user)
> ```
> 
> PS. I removed my previous (misleading) comment.

Yes, chmod works under /home after remounting.

**Comment by sskras** [comment]
> Yes, chmod works under /home after remounting.

Are permissions still lost after `mv` in that case?

**Comment by ArchGuyWu** [comment]
> > Yes, chmod works under /home after remounting.
> 
> Are permissions still lost after `mv` in that case?

Yes, I tried move to /tmp.

**Comment by ArchGuyWu** [comment]
Should I require msys2-runtime to do this, or by myself?

**Comment by ArchGuyWu** [comment]
set umask to 0077 maybe a better way

**Comment by sskras** [comment]
> set umask to 0077 maybe a better way

I am not a developer of MSYS2, but I suggest you to try Midipix project if you are able to cross-compile from Linux:
https://github.com/lalbornoz/midipix_build#2-building-and-deployment

A general overview: https://midipix.org/#sec-midipix

**Comment by dscho** [comment]
> I suggest you to try Midipix project if you are able to cross-compile from Linux

Comments like this one could be so much more useful if they did not leave literally all the effort to others.

In this specific instance, for example, I suspect that the writer has either not even built Midipix successfully (in which case the comment would be a bit troll-ish), or has built it but did not feel it necessary to make it available to others (why, exactly?).

I suggest to try to make such comments (in particular when talking about _other_ projects than the one about which the ticket is, actually) as helpful as possible, leaving little work to the intended recipients so, as to avoid leaving [a somewhat unfortunate impression](https://i.makeagif.com/media/6-10-2016/bVXaNO.gif).
