### ISSUE TITLE
The command in msys2 is executed in terminal app on Windows on ARM platform, sometimes there is no response for a long time.

### ISSUE THREAD

**Issue by ConanNobita** [msys2/Cygwin#228]
Commands in msys2  (x86_64)  sometimes fail to respond, the process seems to be blocked, but commands in clangarm64 do not.
Machine: Huawei Matebook E Go 
CPU: Qualcomm Snapdragon 8cx Gen3
OS: Windows 11 23H2

**Comment by dscho** [comment]
Could you give a concrete example, preferably a repeatable one? And have you tried running such a reproducer through `strace`?

**Comment by ConanNobita** [comment]
For example, when I type the command ```pacman -Syu```, sometimes there is no response. I haven't tried using ```strace``` yet, I will give it a try. If msys2 had an arm64 version, it might be even better.

**Comment by mati865** [comment]
It's not possible to make native AArch64 MSYS2 until Cygwin supports AArch64.

**Comment by jeremyd2019** [comment]
> For example, when I type the command `pacman -Syu`, sometimes there is no response.

This is probably the double-fork issue we've been dealing with for quite some time.  I'm not sure which issue/pr best encapsulates the issue:
https://github.com/msys2/msys2-autobuild/issues/62
https://github.com/msys2/MSYS2-packages/pull/4583
https://cygwin.com/pipermail/cygwin-developers/2024-May/012694.html
https://cygwin.com/pipermail/cygwin/2024-July/256271.html

**Comment by dscho** [comment]
> https://cygwin.com/pipermail/cygwin/2024-July/256271.html

Personally, I prefer https://inbox.sourceware.org/cygwin/a3ec694e-e9d5-04db-fa21-b93b28f7a0d4@jdrake.com/#t because that UI makes it easier to follow responses (or lack thereof).
