### ISSUE TITLE
Is the runtime GPL or LGPL licensed?

### ISSUE THREAD

**Issue by jingyu9575** [msys2/Cygwin#23]
Hi, I wonder which license the runtime `msys-2.0.dll` is distributed with. 
I think the upstream cygwin has changed to LGPL since 2016, and from *winsup/CYGWIN_LICENSE*, it seems that the runtime should be LGPL. However both GPL and LGPL texts are in the project root, and I'm not sure if `msys-2.0.dll` contains code other than *winsup*.
Thank you.

**Comment by Biswa96** [comment]
Why focusing on license instead of the program and code?

**Comment by jingyu9575** [comment]
@Biswa96 I'm interested whether I can distribute closed source programs with MSYS2 runtime. 
Some programs are difficult to compile with MinGW, e.g. [libpinyin](https://github.com/jingyu9575/libpinyin-mingw-utf8) requires several #define patches to work in Windows, but under MSYS2 subsystem it works cleanly. (libpinyin is GPL itself so it does not have license problems.)

**Comment by lazka** [comment]
see https://cygwin.com/licensing.html so LGPL with a static linking exception

**Comment by jingyu9575** [comment]
@lazka Thank you! So it has the same license as cygwin. 
I suggest updating the [PKGBUILD](https://github.com/msys2/MSYS2-packages/blob/c7b6cf444f4ac67129611e15fe95e38b0eb40cc8/msys2-runtime/PKGBUILD#L11) license field, which was written before cygwin switched to LGPL.

**Comment by lazka** [comment]
@jingyu9575 the package contains various cygwin tools besides the cygwin DLL, so I think it's correct that way.

**Comment by mingwandroid** [comment]
Being an open source project we prefer action over suggestions. PR welcome! Thanks!

**Comment by jingyu9575** [comment]
@mingwandroid I've checked it again. At least one of the packaged executable (`dumper.exe`) uses [GPL sources](https://github.com/msys2/msys2-runtime/blob/msys2-3_1_7-release/winsup/utils/dumper.cc), so I think @<span>lazka</span> is correct and the license field should not be changed.

**Comment by mingwandroid** [comment]
I believe this to be a simple oversight on the part of cygwin. They intend the whole thing to be lgpl and i fully support that effort personally. It allows commercial usage.

**Comment by lazka** [comment]
The LICENSE/COPYING files in cygwin git are quite clear on which parts are GPL and which are LGPL, so I don't think this is an oversight.

**Comment by mingwandroid** [comment]
Ah fair enough. Sorry for not checking!
