### ISSUE TITLE
identify arm64 host in uname output?

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/Cygwin#238]
I was recently thinking about how `uname` used to include `-WOW64` for i686-on-x86_64 situations, and that it would be possible to use `IsWow64Process2` to identify and report x86_64-on-ARM64 (and indeed i686-on-ARM64, if backported to 3.3) in a similar way.  That might be useful for stats collection purposes (such as https://github.com/msys2/MSYS2-packages/discussions/2832).

I thought to bring this up on cygwin list, but I already have several outstanding messages there that have never been replied to, and I'd much rather my recent patch for hangs on ARM64 get attention, so I figured I'd memorialize the idea here.

**Comment by dscho** [comment]
This is a great idea! The only challenge I see is to decide what label to use... we clearly do not want to use `aarch64` here lest there is confusion about an _ARM64_ runtime (which does not exist), and also `-WOW64` is inappropriate because it's reserved for i686-on-x86_64, and not for x86_64-on-aarch64...

**Comment by jeremyd2019** [comment]
> This is a great idea! The only challenge I see is to decide what label to use... we clearly do not want to use `aarch64` here lest there is confusion about an _ARM64_ runtime (which does not exist), and also `-WOW64` is inappropriate because it's reserved for i686-on-x86_64, and not for x86_64-on-aarch64...

Technically, there shouldn't be a confusion, because the arch the runtime is built for is in `uname -m`, while the `-WOW64` tag was in `uname -s`:
```console
# uname -s
MSYS_NT-10.0-19045-WOW64

# uname -m
i686
```

Of course, users are prone to confusion 😁 

My first thought was appending `-WOW64-arm64` (or `-aarch64` - I'm not sold on one vs the other) to sysname.

prototype: https://gist.github.com/jeremyd2019/bb17f602da12e0f42aa4ff76848279e8

**Comment by lazka** [comment]
Isn't WOW64 separate? It's not used when emulating x64 on arm64 from what I understand.

**Comment by jeremyd2019** [comment]
I'm not sure - you find out using `IsWow64Process2`, but it does return `IMAGE_FILE_MACHINE_UNKNOWN` for the "process"/"emulated" value, which MSDN says means it is not a WOW64 process.

**Comment by lazka** [comment]
https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/landing/arm-docs/apps-on-arm-x86-emulation.md#how-emulation-works

I don't have a good idea for a name though. XOA64 :)

**Comment by jeremyd2019** [comment]
So you're proposing something more like https://gist.github.com/jeremyd2019/bb17f602da12e0f42aa4ff76848279e8/revisions#diff-b01848fbcc4d8de021593b1f35eb093d8721f33416483b366587de3b20eb187f ?

**Comment by jeremyd2019** [comment]
https://inbox.sourceware.org/cygwin/833327a2-3a62-ed26-e4ba-5302bcdb8000@jdrake.com/T/

**Comment by lazka** [comment]
https://github.com/msys2/msys2-devtools/pull/10
