### ISSUE TITLE
msys2 how to support serial port COMx (x > 127)? 

### ISSUE THREAD

**Issue by shishirong** [msys2/Cygwin#242]
I created a pair of virtual serial ports using [com0com](https://com0com.sourceforge.net/), but they do not appear in /dev/.

**Comment by dscho** [comment]
Do they show up in [Cygwin](https://cygwin.com/)?

**Comment by shishirong** [comment]
I'm not use Cygwin.
but I tried smaller com number, example:
com0com add COM128 <---> COM129 ,   have a ttyS127 in msys2 /dev/,   tty max number is 128?

**Comment by dscho** [comment]
> I'm not use Cygwin.

I know you're not. That's why I asked you to test the issue there, as Cygwin's code is what MSYS2 uses here, and if you could pinpoint it to Cygwin, we would know which code to look at.

**Comment by shishirong** [comment]
Cygwin is same with msys2 . 
com0com add COM127 <---> COM128:  in msys2 or Cygwin:  /dev/ttyS126 /dev/ttyS127
com0com add COM129 <---> COM130: msys2 or Cygwin don't support

![image](https://github.com/user-attachments/assets/7eef55a7-4bbe-4df4-baea-49583fc805de)

**Comment by dscho** [comment]
> Cygwin is same with msys2 .

Then please [report this to Cygwin](https://cygwin.com/problems.html); They are much better equipped to address this problem.

**Comment by shishirong** [comment]
ok，thanks
