### ISSUE TITLE
many import libraries link against incorrect library

### ISSUE THREAD

**Issue by ktbarrett** [msys2/Cygwin#26]
Using an up-to-date Msys2 install I see that `/usr/lib/libc.a`, `/usr/lib/libm.a`, `/usr/lib/libdl.a`, and potentially others use the incorrect name of the msys DLL:

```
dlltool -I /usr/lib/libc.a
msys_2_0.dll
```

There is no DLL of that name. The correct name is likely `msys-2.0.dll`. `/usr/lib/libg.a` gets this right even though it is a part of the same package: `msys2-runtime-devel`. Also of note is that these are import libraries using the suffix `.a`, while most other packages use `.dll.a`. Not sure if that's an issue though.

I ran into this issue because of msys2/MSYS2-packages#2357. `ctypes.util.find_library('dl')` returns `msys_2_0.dll` which will not load in `ctypes.CDLL()`.

**Comment by dscho** [comment]
The most likely culprit is this line: https://github.com/msys2/msys2-runtime/blob/e68ccdf6e5e775b01f43c722b4963da81f4bd57c/winsup/cygwin/speclib#L38

In my tests, the output of `nm -Apg --defined-only libmsys-2.0.a` contains only this line that matches `/ I _?(.*)_dll_iname/o`:

```
../build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin/libmsys-2.0.a:d001717.o:0000000000000000 I msys_2_0_dll_iname
```

The `winsup/cygwin/speclib` file of the MSYS2 runtime is unchanged from Cygwin's: https://github.com/msys2/msys2-runtime/blob/cygwin-3_1_7-release/winsup/cygwin/speclib#L38, but Cygwin does not have this problem, of course: the file name `cygwin1.dll` does not contain any dashes nor dots.

I could imagine that the best work-around might look like this:

```diff
diff --git a/winsup/cygwin/speclib b/winsup/cygwin/speclib
index b90096040..617a9c2ca 100755
--- a/winsup/cygwin/speclib
+++ b/winsup/cygwin/speclib
@@ -37,6 +37,7 @@ while (<$nm_fd>) {
     study;
     if (/ I _?(.*)_dll_iname/o) {
 	$dllname = $1;
+	$dllname =~ s/_2_0/-2.0/;
     } else {
 	my ($file, $member, $symbol) = m%^([^:]*):([^:]*(?=:))?.* T (.*)%o;
 	next if !defined($symbol) || $symbol =~ $exclude_regex;
```

@ktbarrett would you mind testing this, and if it works, whip up a PR?

**Comment by ktbarrett** [comment]
Maybe. I've never done a build of the runtime. I'm guessing pacman will handle it. I'll report back in a couple days either way.

**Comment by dscho** [comment]
We do have a GitHub workflow in `.github/workflows/` that you can look at for inspiration. Or you just use it to build the thing (you will probably want to [upload the build artifacts](https://github.com/marketplace/actions/upload-a-build-artifact), which our workflow does not do, so you need to edit it a bit).

**Comment by ktbarrett** [comment]
Tried the fix. It seems to work. I does seem like a hack IMO, but whatever.
```
kaleb@rigatoni MSYS ~/msys2-runtime
$ find x86_64-pc-msys/winsup/cygwin/ -name "*.a" -exec dlltool -I {} \;
x86_64-pc-msys/winsup/cygwin/libacl.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libautomode.a
dlltool: Unable to determine dll name for `x86_64-pc-msys/winsup/cygwin/libautomode.a' (not an import library?)
x86_64-pc-msys/winsup/cygwin/libbinmode.a
dlltool: Unable to determine dll name for `x86_64-pc-msys/winsup/cygwin/libbinmode.a' (not an import library?)
x86_64-pc-msys/winsup/cygwin/libc.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libdl.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libgmon.a
dlltool: Unable to determine dll name for `x86_64-pc-msys/winsup/cygwin/libgmon.a' (not an import library?)
x86_64-pc-msys/winsup/cygwin/libm.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libmsys-2.0.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libmsys0.a
dlltool: x86_64-pc-msys/winsup/cygwin/libmsys0.a: malformed archive
x86_64-pc-msys/winsup/cygwin/libpthread.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libresolv.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/librt.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libssp.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/libtextmode.a
dlltool: Unable to determine dll name for `x86_64-pc-msys/winsup/cygwin/libtextmode.a' (not an import library?)
x86_64-pc-msys/winsup/cygwin/libtextreadmode.a
x86_64-pc-msys/winsup/cygwin/libutil.a
msys-2.0.dll
x86_64-pc-msys/winsup/cygwin/msysdll.a
msys-2.0.dll
```
