### ISSUE TITLE
Handle Ctrl+C interupts for Mingw Executables

### ISSUE THREAD

**Issue by naveen521kk** [msys2/Cygwin#29]
see https://github.com/msys2/MINGW-packages/issues/7650

Simple reproducer,
- open minitty
- Install MinGW-python
- run `python`
- Press Ctrl+C
traceback would be missing in minitty while the same is should when python is run in cmd

This cause the executable from setuptools, like `pip.exe` to not kill the child process as described https://github.com/msys2/MINGW-packages/issues/7650

When discussing on [Discord](https://discord.com/channels/792780131906617355/794220101741838401/815593216329515050) a few days ago, lazka pointed out that this is fixed in Git for Windows runtime.

The corresponding issue on Git for Windows: https://github.com/git-for-windows/git/issues/1248
These are the patches:
- https://github.com/git-for-windows/msys2-runtime/commit/e8dd881efeb5632e861e214db7686d868a420038
- https://github.com/git-for-windows/msys2-runtime/commit/24fb4e4b1c55753a38ac472d7b8f1ba59b0eee6c
- https://github.com/git-for-windows/msys2-runtime/commit/3c7a25ef94adc222f7f83fb10e453201f3d6ec57
- https://github.com/git-for-windows/msys2-runtime/commit/0a1f55b738ef3970fdcc155d6d8fc29dc1d7596e

**Comment by dscho** [comment]
@naveen521kk how about cherry-picking these commits into an easy-to-review PR?

**Comment by agorgl** [comment]
I suppose this is related to this? https://github.com/mintty/mintty/issues/684#issuecomment-841115784
