### ISSUE TITLE
Nested msys2 vscode integrated terminal has wrong PATH 

### ISSUE THREAD

**Issue by alanlivio** [msys2/Cygwin#43]
My vscode use msys2 as integrated terminal using the following cmdline:

```
cmd C:\\tools\\msys64\\msys2_shell.cmd -defterm -mingw64 -no-start -use-full-path -here
```

The PATH seems correct in the integrated terminal: 
```bash
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mnt/c/Windows/system32:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/ProgramData/chocolatey/lib/gsudo/bin:/mnt/c/Program Files (x86)/GNU/GnuPG/pub:/mnt/c/Program Files/OpenJDK/openjdk-8u282-b08-jre/bin:/mnt/c/Program Files/CMake/bin:/mnt/c/Program Files/nodejs:/mnt/c/tools/msys64/mingw64/bin:/mnt/c/tools/msys64/usr/bin
```
Then, in this VScode terminal, I call another vscode in a diferent folder:

`cmd code another-folder`

The new terminal, inside this new vscode instance have prblems in the $PATH:

```bash
$ echo $PATH
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:C:\Windows\system32;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\ProgramData\chocolatey\lib\gsudo\bin;
```

**Comment by Biswa96** [comment]
Explain this thing `cmd code another-folder`. What is happening there? Are you executing that command in previous msys2 environment? What is VScode doing there? Any way to reproduce the issue without VSCode?

**Comment by naveen521kk** [comment]
See https://stackoverflow.com/a/48016561 for configuring MSYS2 shell with VSCode, it's documented in https://www.msys2.org/wiki/Launchers/

**Comment by dscho** [comment]
> Explain this thing `cmd code another-folder`

I _think_ what they meant to describe is that they call `code` (i.e. VS Code) on another folder, i.e. opening a separate VS Code. At least when I call `code .` in a Bash, it opens the current folder in a new VS Code, and I assume that `cmd code <folder>` does the equivalent.

Obviously, it would be better if @alanlivio answered your question, though.

**Comment by alanlivio** [comment]
hi. Thanks everyone for the feedbacks. The following screenshots detais:

In first msys2 VScode integrated terminan
![image](https://user-images.githubusercontent.com/604808/120820184-b02d7700-c52a-11eb-806b-6e803234a3da.png)


In secondmsys2 VScode integrated terminal
![image](https://user-images.githubusercontent.com/604808/120820296-caffeb80-c52a-11eb-9e50-4d066859f4e6.png)

The path in the second has wrong windows paths.

**Comment by dscho** [comment]
Why not call `code <folder>` directly, i.e. _skip_ the `cmd`? You're in a Bash, after all, no need to go through an extra layer.

**Comment by alanlivio** [comment]
hi @dscho 

> Why not call code <folder> directly, i.e. skip the cmd? 
I do that inside the integrated terminal.

Maybe I was not clear about how the VSCode open the integrated terminal. 
It directly call the msys script. Please see the my VSCode settings.json that define that.

```
  "terminal.integrated.profiles.windows": {
    "msys": {
      "overrideName": true,
      "path": "C:\\tools\\msys64\\msys2_shell.cmd",
      "args": [
        "-defterm",
        "-mingw64",
        "-no-start",
        "-use-full-path",
        "-here"
      ],
    },
  },
```

**Comment by dscho** [comment]
@alanlivio I was talking about the way _you_ call _VS Code_. You said that you call it inside an integrated terminal, using

```
cmd code <folder>
```

And I challenged you to avoid using that `cmd` that seems totally unnecessary. Just use

```
code <folder>
```

and then tell us whether this works around your problem.

**Comment by alanlivio** [comment]
hi @dscho. sorry for the delay. It is open normally from the windows taskbar. 
The problems as I said if a open another code ($ code . ) from the msys bash as integrated terminal of the first.
If you take a look at the images added above, you see that the second msys bash add some strange ';' characters.

**Comment by dscho** [comment]
@alanlivio you sure sent me on a wild Goose chase by mentioning VS Code! For the record, a much, much simpler reproducer is to call `/msys2_shell.cmd -full-path` in an MSYS2 Bash.

**Comment by alanlivio** [comment]
Hi @dscho sorry about that =)
Indeed Idid call directly from msys shell. But I am glad that the problem was found.

**Comment by dscho** [comment]
@alanlivio ping about https://github.com/msys2/MSYS2-packages/pull/2805#issuecomment-1013167122. I would really hate to feel as if I did all the work and you did not even bother to verify the fix.

**Comment by alanlivio** [comment]
Hi @dscho. Thanks for the ping. I commented there.
