### ISSUE TITLE
Access to inaccessible directories (with no permissions) is allowed through the msys2 terminal in Windows Server 2016 and Windows Server 2019

### ISSUE THREAD

**Issue by pedropalau** [msys2/Cygwin#45]
## Describe the issue

We have an application in `golang` that implements a test that works well in non-Windows Server installations. 

Recently, we configured [GitHub Actions](https://github.com/actions/virtual-environments) for our application, and the only available Windows versions are **Windows Server 2016** and **Windows Server 2019**. We are currently using the Windows Server 2019 version.

The test in mention started failing. Basically, it tries to access an inaccessible folder without any permissions. A `chmod` representation of this permission could be `0000`. We found that a folder and its content can be accessed through the **msys2** terminal even with that permission. 

I don't know if this is a known issue or the right behavior in **msys2**. It's my understanding that Windows Server versions might manage ACL permissions quite differently from non-Windows Server versions. I've looked in the issues list and didn't find anything that could help me get this working. 

If this is an unknown bug in **msys2**, it means that an attacker can use it to access system folders even when it's not supposed to happen.

## Steps to Reproduce the Problem

1. Creates a directory in the `Temp` location.
2. Removes all permissions and inheritance from the `Security` tab inside folder's `Properties`.
3. The folder should be inaccessible and it content can't be read.
4. Open the `msys2` terminal.
5. Access that folder through the terminal, for example with `ls -la /c/Users/%USERNAME%/AppData/Local/Temp/%FOLDER%`
6. All the content of the directory is listed and can be accessed.

## Additional Context: 

- Windows Server 2016 Datacenter version 64bit
- Windows Server 2019 Datacenter version 64bit

**Comment by jeremyd2019** [comment]
Confirmed that this is intentional, and using the `SeBackupPrivilege`/`FILE_OPEN_FOR_BACKUP_INTENT` method:
https://github.com/msys2/msys2-runtime/blob/msys2-3_2_0-release/winsup/cygwin/sec_helper.cc#L523-L528

**Comment by pedropalau** [comment]
> Confirmed that this is intentional, and using the `SeBackupPrivilege`/`FILE_OPEN_FOR_BACKUP_INTENT` method:
> https://github.com/msys2/msys2-runtime/blob/msys2-3_2_0-release/winsup/cygwin/sec_helper.cc#L523-L528

Interesting. So, if I understood correctly, this is done like this, because the process is executed with administrator rights?

**Comment by pedropalau** [comment]
> You might bring it up with them at mailto:[cygwin@cygwin.com](mailto:cygwin@cygwin.com).

Okay, thanks for the info.

**Comment by jeremyd2019** [comment]
> Interesting. So, if I understood correctly, this is done like this, because the process is executed with administrator rights?

Yes.  But under the normal Windows API this is not sufficient, you have to also enable the `SeBackupPrivilege` in the process token (it's disabled by default even when granted), and then open the file with the `FILE_OPEN_FOR_BACKUP_INTENT` flag.  So cygwin went out of their way to bypass ACLs when possible.  Similar with the `SeRestorePrivilege` for writes

**Comment by pedropalau** [comment]
Okay, I'm going to write them and see how can I fix this behavior.

Thanks, @jeremyd2019, your help is appreciated.

**Comment by jeremyd2019** [comment]
No problem.  The Windows security model is an area of interest of mine, so I had a pretty good idea what to look for.

**Comment by pedropalau** [comment]
I have checked. I would never have gotten to this point on my own. :)

**Comment by jeremyd2019** [comment]
I saw you got a reply on the cygwin list: https://cygwin.com/pipermail/cygwin/2021-May/248596.html

I am working on packaging cygutils, which contains `cygdrop`, in msys2/MSYS2-packages#2518.  I have confirmed that it works to drop the privileges so that cygwin cannot use them to bypass ACLs.

**Comment by pedropalau** [comment]
Hi @jeremyd2019

> I saw you got a reply on the cygwin list: https://cygwin.com/pipermail/cygwin/2021-May/248596.html

Yeap, they have been very nice.

> I am working on packaging cygutils, which contains `cygdrop`, in [msys2/MSYS2-packages#2518](https://github.com/msys2/MSYS2-packages/pull/2518). I have confirmed that it works to drop the privileges so that cygwin cannot use them to bypass ACLs.

Thank you very much. You're my hero. When do you think this will be merged and available for the rest of us?

**Comment by Biswa96** [comment]
> When do you think this will be merged and available for the rest of us?

* After merging the pull request in MSYS2-packages repo, the new package will be pending here https://packages.msys2.org/queue
* After uploading the package to main pacman repository, the new package will be shown here https://packages.msys2.org/updates. At this moment everyone can download/install it.

**Comment by pedropalau** [comment]
Hi @jeremyd2019

I just realized that this is not going to help me. To get this working, I should use the `cygdrop` command with the golang process and that doesn't feel right.

I don't know if that makes sense for you? I would like to know what do you think about this.

**Comment by jeremyd2019** [comment]
you'd need to run your tests through cygdrop.  Depending on the permissions github sets up you could probably run your whole process through cygdrop.

**Comment by jeremyd2019** [comment]
cygutils now appears to be in the repo. (though if you use a mirror it may take a while to show up).  what I would do for a quick test you could change your CI to add cygutils to https://github.com/coyim/coyim/blob/main/.github/workflows/ci.yml#L106 (BTW, why not install mingw-w64 packages there so they'll be cached, instead of manually via pacman in a later step? and the updates after setup-msys2 shouldn't be necessary). and change https://github.com/coyim/coyim/blob/main/.github/workflows/ci.yml#L131 to `cygdrop make `...

**Comment by pedropalau** [comment]
Hi @jeremyd2019,

I want to thank you for all the help. We fixed the problem using the `cygdrop` command, and everything looks good now.

I think this issue could be closed now.

Again, thank you very much.
