### ISSUE TITLE
Try finding CtrlRoutine with GetProcAddress

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/Cygwin#51]
Oddly enough, this hack seems to work:
```diff
diff --git a/winsup/utils/getprocaddr.c b/winsup/utils/getprocaddr.c
index 80b399c..beafc10 100644
--- a/winsup/utils/getprocaddr.c
+++ b/winsup/utils/getprocaddr.c
@@ -164,9 +164,9 @@ main (int argc, char **argv)
    * because here because that symbol isn't exported.
    */

-  if (strcmp (argv[1], "CtrlRoutine"))
+  if (TRUE || strcmp (argv[1], "CtrlRoutine"))
     {
-      HINSTANCE kernel32 = GetModuleHandle ("kernel32");
+      HINSTANCE kernel32 = GetModuleHandle (strcmp(argv[1], "CtrlRoutine") ? "kernel32" : "kernelbase");
       if (!kernel32)
         return 1;
       void *address = (void *)GetProcAddress (kernel32, argv[1]);
```

Maybe it could look in `KERNELBASE` for `CtrlRoutine` the same way it looks in `KERNEL32` for ExitProcess, and if it's not found fall back to using dbghelp (assuming there's a downlevel version of Windows for which that didn't work, that prompted the dbghelp approach in the first place).

_Originally posted by @jeremyd2019 in https://github.com/msys2/msys2-runtime/issues/47#issuecomment-865556700_

**Comment by jeremyd2019** [comment]
I poked win7 with good old dependency walker, and it looks like `CtrlRoutine` is exported from `KERNEL32` on Win7.  I already determined that `CtrlRoutine` is exported from `KERNELBASE` on Win10.  Perhaps try finding it in both, before falling back to groveling the stack for it.

/cc @dscho

**Comment by Biswa96** [comment]
This seems to be too hacky for a critical program like cygwin.

**Comment by jeremyd2019** [comment]
The current state of this is that it uses debugging functions to try to find the start address of the (undocumented) function that called the ctrl handler based on the call stack.  I'm just proposing that it try to avoid doing that by checking a couple of DLLs where it's been seen to exist as an exported symbol.  I see that as *less* hacky then trying to find it with dbghelp.

**Comment by jeremyd2019** [comment]
If you are referring to the whole <kbd>Ctrl</kbd>+<kbd>C</kbd> handling code, I definitely wouldn't have expended this much energy and hackery on it.  But I've never seen the issue in real life, because I don't use mintty, only Windows native conhost or recently Windows Terminal.  In that case Windows handles this all behind the scenes as it was designed to do, and requires no hacks into that handling to try to separate processes that as far as Windows is concerned share a console.

**Comment by dscho** [comment]
> 
> 
> This seems to be too hacky for a critical program like cygwin.

Well, uhm... if you find a less hacky way to emulate <kbd>Ctrl</kbd>+<kbd>C</kbd>, let's hear it, @Biswa96!

I would have _loved_ to find such a way, but couldn't. Sending a ConsoleCtrlEvent directly would take down every process attached to the same console, including, you guessed it, MinTTY.

And I spent _months_ researching this.

So I hope you understand how dismissive your comment sounds to me.

**Comment by Biswa96** [comment]
I didn't mean to hurt anyone. I meant that calling an undocumented function from KernelBase.dll may be risky.

**Comment by dscho** [comment]
You should have called that out in the original PR, then. Or in the PR we merged years ago in Git for Windows, where it works reliably ever since.
