### ISSUE TITLE
Is it possile to bypass the 256 bytes MAX_PATH limit?

### ISSUE THREAD

**Issue by nyfair** [msys2/Cygwin#55]
As we all know, most of the file systems on linux have this limitation.
On windows, the preset limit is 260 characters and it can be even more through modify registry value.

```
echo 'md "(エアコミケ4) (一般コミック) [这尼玛什么乱七八糟瞎起名坑爹作者] 名字起的这么长到底能有啥问题啊！这种几
十年前一拍脑袋就决定的东西今天看起来简直莫名其妙啊！为什么事情会变成这个样子呢？这种粗暴一刀切的限制在今天为什么还能存在啊"' > 1.bat && cmd < 1.bat
cd '(エアコミケ4) (一般コミック) [这尼玛什么乱七八糟瞎起名坑爹作者] 名字起的这么长到底能有啥问题啊！这种几十年前一拍脑袋就决定的东西今天看起来简直莫名其妙啊！为什么事情会变成这个样子呢？这种粗暴一刀切的限制在今天为什么还能存在啊'

cd: File name too long
cd: Unknown error trying to locate directory '(エアコミケ4) (一般コミック) [这尼玛什么乱七八糟瞎起名坑爹作者] 名字起的这么长到底能有啥问题啊！这种几十年前一拍脑袋就决定的东西今天看起来简直莫名其妙啊！为什么事情会变成这个样子呢？这种粗暴一刀切的限制在今天为什么还能存在啊'
```

Name of the created folder has 118 characters and 331 bytes, it is a valid windows folder name and most of MINGW64 tools can handle it correctly only if it was called from powershell or cmd

**Comment by dscho** [comment]
Whatever support there is for longer paths in the MSYS2 runtime would be inherited from the Cygwin runtime. Maybe raise the issue with the kind Cygwin folks?

**Comment by nyfair** [comment]
Thank you for your answer. I'll try to modify this value and do more test

**Comment by dscho** [comment]
> 
> 
> Thank you for your answer. I'll try to modify this value and do more test

If you increase the value, you will have to adjust your registry accordingly. See https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd for details.

**Comment by dscho** [comment]
(And you'll have to add that manifest entry.)

**Comment by nyfair** [comment]
After testing for a while, I'm quite satisfy with this.
Except for adjusting registry, the only thing need to do is to change `__NAME_MAX` in `winsup/cygwin/include/cygwin/limits.h`.
If the length of given filename is beyond registry limits, the runtime will just show a `File Not Found` message.
I can't say this modification is safe and it may contain unknown inconsistent bugs, but at least it really helps me to solve a lot of annoying problems.

Thank you once again for your help.
