### ISSUE TITLE
Update to cygwin 3.3.x

### ISSUE THREAD

**Issue by lazka** [msys2/Cygwin#61]
https://cygwin.com/git/?p=newlib-cygwin.git;a=shortlog;h=refs/heads/cygwin-3_3-branch

https://cygwin.com/pipermail/cygwin-announce/2021-October/010268.html

https://cygwin.com/pipermail/cygwin-announce/2021-October/010269.html

**Comment by dscho** [comment]
v3.3.2 PR: https://github.com/msys2/msys2-runtime/pull/63
