### ISSUE TITLE
Windows Terminal, unicode issue

### ISSUE THREAD

**Issue by hummeleBop** [msys2/Cygwin#66]
Hello there,

The following issue is related to the msys2 runtime. I think it's relevant to link it directly here.

[git for windows / github issue 3281](https://github.com/git-for-windows/git/issues/3281)

Is there a way to make msys2 behave properly with unicode in the windows terminal ?

**Comment by dscho** [comment]
The patch at https://cygwin.com/pipermail/cygwin-patches/2021q4/011542.html is currently under discussion. Once it is integrated into Cygwin, we will also integrate it into the MSYS2 runtime.

**Comment by hummeleBop** [comment]
It's clearly a really great news !!!! Thanks !!!
