### ISSUE TITLE
Request: Ctrl+C bugfix to be ported from cygwin

### ISSUE THREAD

**Issue by aont** [msys2/Cygwin#68]
I submitted an issue on MSYS2-packages repo.
https://github.com/msys2/MSYS2-packages/issues/2665

As I commented there, I submitted a bug report to cygwin mailing list.
https://cygwin.com/pipermail/cygwin/2021-November/249749.html

Now cygwin runtime is fixed.
https://github.com/cygwin/cygwin/commit/561767fc5942746bf52c4b9f630e6a79659896a0
https://github.com/cygwin/cygwin/commit/2221bebd718d2eb20a8cf352a15b15599067573b
https://github.com/cygwin/cygwin/commit/eb628ca8eac37cc810d6b77c5fa376ce8125b570

Since, this bug is found to be originated from msys2-runtime, I submit this issue here.

I request these patches to be ported to msys2.

**Comment by aont** [comment]
https://github.com/cygwin/cygwin/commit/d4e42ceb96b590f214b16442dc73f0c05db41e09
Though this is not related to my issue, I want this patch to be ported too.

**Comment by dscho** [comment]
@aont the question is: do you want this enough to fork this repository, clone it, branch off of `msys2-3_3_2-release`, cherry-pick the changes, then push and open a PR here?

**Comment by jeremyd2019** [comment]
https://github.com/msys2/msys2-runtime/commit/b3d2f35cb1a62daf92d88e1aecc2a235d843dbca is already on the msys2-3_3_2-release branch (it was included in cygwin 3.3.2).  The other commits referenced here are already included as well.

**Comment by jeremyd2019** [comment]
for the record, these are 
a4bda4f62652321a78909f31b39b40b4ede5c1c4
ea64a781c77225f07e70e781a889b7d471bc7eec
b01b5e45e96919b8776dd0569fd76d57866e29c2

**Comment by aont** [comment]
@dscho
Thank you for the reply.
Since I cannot build msys2 runtime myself, I cannot confirm the bug be fixed. 
I read this and tried, but no luck.
https://github.com/sowmyasudhakar/angular-phonecat/blob/master/Building-msys2-runtime.md

**Comment by aont** [comment]
@jeremyd2019
Thank you for telling me that those patches are already committed to msys2-runtime.
I am looking forward to the new runtime binary.

**Comment by Biswa96** [comment]
The new _unsigned_ packages are stored here https://repo.msys2.org/staging/. You can test msys2-runtime package from there using `pacman -U` command.

**Comment by dscho** [comment]
>  Since I cannot build msys2 runtime myself, I cannot confirm the bug be fixed.

That is why I suggested opening a PR. It would build the MSYS2 runtime in a GitHub workflow, and you could then download it from the build.

In fact, you can do so right now. Pick any recent build from https://github.com/msys2/msys2-runtime/actions/workflows/build.yaml, download the artifacts, and -- bam! -- you can contribute more effectively to the MSYS2 project.
