### ISSUE TITLE
Directories ending with ".lnk" should not be handled as links

### ISSUE THREAD

**Issue by jobor** [msys2/Cygwin#81]
I want to create two directories, "foo" and "foo.lnk".

The following command sequence works fine:
```
alb@bla MINGW64 /d/TEMP
$ mkdir foo

alb@bla MINGW64 /d/TEMP
$ mkdir foo.lnk

alb@bla MINGW64 /d/TEMP
$ ls
foo/  foo.lnk/
```

But if the directory ending with ".lnk" is created first, we run into an error:
```
alb@bla MINGW64 /d/TEMP
$ mkdir foo.lnk

alb@bla MINGW64 /d/TEMP
$ mkdir foo
mkdir: cannot create directory ‘foo’: File exists
```

Presumably, ``foo.lnk`` is handled as link (or shortcut) due to the .lnk suffix.

Windows shortcuts (.lnk files) are always *files*, and directories ending with .lnk are just directories.
Msys2 should not handle such directories as links.

While the above example is a constructed one, here's the issue which I stumbled upon: It's not possible to clone the following git repository with msys2 git: 

```
alb@bla MSYS /d/TEMP
$ git clone --depth 1 git://code.qt.io/qt/qtbase.git
...output omitted, but this will fail. See the next command why that is.

alb@bla MSYS /d/TEMP/qtbase
$ git reset --hard
fatal: cannot create directory at 'tests/auto/corelib/io/qdir/testdir/dir.lnk/subdir': File exists
```

Git failed to create a certain directory. Because the directory ``tests/auto/corelib/io/qdir/testdir/dir.lnk/subdir.lnk`` is also part of the repo and was created before.

Side note: Interestingly, git from https://gitforwindows.org/ can clone this repo just fine, though it's also msys2-based.

**Comment by dscho** [comment]
> Side note: Interestingly, git from https://gitforwindows.org/ can clone this repo just fine, though it's also msys2-based.

I think that conundrum might be easy to solve: you most likely use `/usr/bin/git.exe`, which is an MSYS program, whereas Git for Windows uses `/mingw64/bin/git.exe`, which is a _MINGW_ program. And MINGW programs are not subject to the MSYS2 runtime.

> Presumably, `foo.lnk` is handled as link (or shortcut) due to the .lnk suffix.

I thought so at first, too, but that's not the case: https://github.com/msys2/msys2-runtime/blob/27276c6ba0443413bff727a180a8d572eb8c7fd2/winsup/cygwin/path.cc#L3542-L3545. You can also verify this by calling `stat foo`: it does not claim to find a link.

> ```console
> $ mkdir foo
> mkdir: cannot create directory ‘foo’: File exists
> ```

This reproduces here, too. When I run this through `strace.exe`, I see this line:

```
   75  133976 [main] mkdir 12323 __set_errno: int mkdir(const char*, mode_t):347 setting errno 17
```

The line 347 corresponds to this code: https://github.com/msys2/msys2-runtime/blob/27276c6ba0443413bff727a180a8d572eb8c7fd2/winsup/cygwin/dir.cc#L347

Which means that `fh->exists()` returns `true`. The method is defined [here](https://github.com/msys2/msys2-runtime/blob/27276c6ba0443413bff727a180a8d572eb8c7fd2/winsup/cygwin/fhandler.h#L239) and simply hands off to the `path_conv` class' [`exists()` method](https://github.com/msys2/msys2-runtime/blob/27276c6ba0443413bff727a180a8d572eb8c7fd2/winsup/cygwin/path.h#L230), which looks at some `fileattr` field. Apparently that one is populated, and this probably happens in the `check()` method, but I see code that should prevent this from happening: https://github.com/msys2/msys2-runtime/blob/27276c6ba0443413bff727a180a8d572eb8c7fd2/winsup/cygwin/path.cc#L3576-L3583

**Comment by dscho** [comment]
@jobor I hope that the [PR build](https://github.com/msys2/msys2-runtime/runs/4843914425?check_suite_focus=true) passes. When/if it does, could I ask you to download the build artifacts, replace your local `msys-2.0.dll` with the version contained in those artifacts, and verify that it fixes your issue?

**Comment by jobor** [comment]
Thanks for the thorough analysis and the fix! Will test once the build went through.

**Comment by jobor** [comment]
Your patch fixes both, the mkdir issue and the git clone issue.
Thanks for the swift fix!
