### ISSUE TITLE
Ctrl-C interrupts the whole ssh session while catching by in interactive mode

### ISSUE THREAD

**Issue by pnuzhdin** [msys2/Cygwin#83]
The issue:
1. Open `cmd.exe`.
2. Run `C:\msys64\usr\bin\ssh.exe -v somehost`.
3. While in the interactive session run some long-running process e.g. `top`.
4. Press `Ctrl+C` to interrupt the long-running process inside the interactive session.

Observe: The whole interactive ssh session is terminated with the following debug output:
```
debug1: channel 0: free: client-session, nchannels 1
Killed by signal 2.
```

At the same time if you run another MSYS2 package e.g. `vim` instead of `ssh`, `Ctrl+C` works correctly so I'm not sure does it relate to MSYS2 runtime or just OpenSSH package.

**Comment by crrodriguez** [comment]
Observing the same behaviour with ssh.exe shipped with git.. this breaks all workflow for me.

**Comment by dscho** [comment]
Can you try again after setting `MSYS=enable_pcon`?

**Comment by pnuzhdin** [comment]
> Can you try again after setting `MSYS=enable_pcon`?

Thanks, it fixes the issue for me!

**Comment by crrodriguez** [comment]
> Can you try again after setting `MSYS=enable_pcon`?

that restores the correct behaviour, thanks.

**Comment by jeremyd2019** [comment]
Just to clarify, are you talking about running ssh from cmd directly, or running cmd from bash, and then running ssh in that cmd?  I tried to reproduce with the former and it didn't seem to reproduce.  But there was a commit to upstream cygwin recently that claims to fix a cygwin -> native -> cygwin Ctrl-C issue that seems like it might be related

Update: even from bash -> cmd -> msys2 ssh I still can't dupe it

**Comment by jeremyd2019** [comment]
I can dupe with Git for Windows but not with "stock" msys2.

**Comment by dscho** [comment]
@pnuzhdin please test with [the artifact](https://github.com/msys2/MSYS2-packages/suites/5310719289/artifacts/165102515) from the PR with the proposed fix that is under review.

**Comment by dscho** [comment]
Well, now you can simply update...

**Comment by pnuzhdin** [comment]
@dscho @jeremyd2019 thanks! I've updated msys and now it works properly even without `MSYS=enable_pcon`

**Comment by pnuzhdin** [comment]
It seems this issue is reproduced again for:
```
msys2-launcher 1.5-1
msys2-runtime 3.3.5-1
```

And having `MSYS=enable_pcon` doesn't help.

**Comment by dscho** [comment]
@pnuzhdin any chance that you can bisect through the recent patches to figure out which one re-introduced the regression?

**Comment by pnuzhdin** [comment]
@dscho I'm unable to do this, sorry

**Comment by dscho** [comment]
> @dscho I'm unable to do this, sorry

No worries, I can't do it either.

**Comment by not-a-user** [comment]
On a fresh msys2 install (openssh 8.9p1-3, msys2-runtime 3.3.5-3) this problem shows up when 
using a **ProxyCommand** and the actual proxy command is a plain Windows (non-msys) program. With a direct ssh into the same box CTRL-C works as expected.
