### ISSUE TITLE
Drop QueryUnbiasedInterruptTime patch with 3.4

### ISSUE THREAD

**Issue by lazka** [msys2/Cygwin#84]
In the current active branch this is da43030d3aa5d1552a3f22

I noticed it got dropped upstream now because it's a <win7 thing, so we can drop it too on the next rebase: https://sourceware.org/git/?p=newlib-cygwin.git;a=commitdiff;h=047eaf9a6b36881a15e43cbea333725b8e59a3b4;hp=b095628ecff1831b250f34d3b6b5787b3f247d63

**Comment by dscho** [comment]
Did we silently drop Vista support? I thought we still officially supported it...

**Comment by lazka** [comment]
Sorry, I should have been more clear. I meant the next version rebase for 3.4 which drops vista support anyway.

(MSYS2 itself dropped vista support 2-3 years ago)

**Comment by lazka** [comment]
This was done in #120 long ago
