### ISSUE TITLE
unwanted Memory debug

### ISSUE THREAD

**Issue by weberjn** [msys2/Cygwin#87]
The last update resulted in all commands outputting a memory debug:
```
$ ls
      0 [main] bash (12028) shared_info::initialize: size of shared memory region changed from 57272 to 56248
                                                                                                                   0 [main] ls (9956) shared_info::initialize: size of shared memory region changed from 57272 to 56248
saved  work/
```

**Comment by dscho** [comment]
That would suggest to me that you still had an MSYS2 process somewhere, i.e. that you run with two incompatible MSYS2 runtime versions.

**Comment by weberjn** [comment]
You're right, I have just looked, there was still an sshd in the background. Now the problem is gone.

Thanks.
