### ISSUE TITLE
Default to enable_pcon

### ISSUE THREAD

**Issue by lazka** [msys2/Cygwin#98]
We initially said that we'll enable it once there is a cygwin release without conpty fixes, but that hasn't happened.

Still it would be nice to have all those console using apps to just work by default.

@dscho could we try switching the default in this repo, or should we do it in a downstream patch first?

**Comment by dscho** [comment]
> @dscho could we try switching the default in this repo, or should we do it in a downstream patch first?

Let's do it here, by dropping (reverting) https://github.com/msys2/msys2-runtime/commit/b74f834aa69dc0b188d1b971fbd2014f5f4593bc

**Comment by lazka** [comment]
ok, thanks. I'll enable it in the MSYS2 packaging CIs first to make sure it doesn't break anything package building related.

**Comment by lazka** [comment]
> I'll enable it in the MSYS2 packaging CIs first to make sure it doesn't break anything package building related.

I didn't see any issues there.

So next is the update to 3.3.6, and after that has settled I'll try switching on pcon.

**Comment by dscho** [comment]
> > I'll enable it in the MSYS2 packaging CIs first to make sure it doesn't break anything package building related.
> 
> I didn't see any issues there.
> 
> So next is the update to 3.3.6, and after that has settled I'll try switching on pcon.

Sounds good to me!

**Comment by lazka** [comment]
done in #102
