### ISSUE TITLE
Empty variables are silently deleted.

### ISSUE THREAD

**Issue by eli-schwartz** [msys2/Cygwin#99]
Windows is perfectly okay with environment variables of the form `"MESON_SUBDIR="`, at least I can set such a variable in e.g. a python script and communicate it to another process. Although cmd.exe's `set` IIUC will delete it? But msys2 is not a cmd.exe emulator...

However, trying to run this fails:
```
"env" "MY_ENV=1" "MESON_SOURCE_ROOT=D:\a\meson\meson\test cases\common\51 run target" \
    "MESON_BUILD_ROOT=D:\a\meson\meson\tmp59june4u" "MESON_SUBDIR=" \
    "MESONINTROSPECT=D:\a\_temp\msys64\mingw32\bin\python3.exe D:\a\meson\meson\meson.py introspect" \
    "D:\a\_temp\msys64\mingw32\bin\python3.exe" "D:/a/meson/meson/test cases/common/51 run target/check-env.py" \
    "../test cases/common/51 run target" "." "../test cases/common/51 run target/"
```

```
Traceback (most recent call last):
  File "D:\a\meson\meson\test cases\common\51 run target\check-env.py", line 8, in <module>
    assert 'MESON_SUBDIR' in os.environ
AssertionError
```

This was brought up e.g. in https://github.com/msys2/MINGW-packages/issues/1599 in the past.

...

It seems very wrong for the msys2 runtime to do this. If I run `python3.exe basically-env.py "MESON_SUBDIR=" <script>` it works flawlessly, but if I run `env.exe "MESON_SUBDIR=" <script>` it refuses to work because it's trying to emulate cmd.exe instead of Unix?

Unfortunately, Meson *needs* this functionality, because "the concept of being empty" is crucial information that needs to be passed from one process to another. I would like to pass this information via the most efficient program for setting such information, but it looks like I might need to restrict that to "real unixes".

Thoughts? Is it possible this restriction can be lifted?

**Comment by dscho** [comment]
I _think_ the original rationale was that setting an environment variable to an empty value deletes it in `CMD`, and that this behavior should be replicated by the MSYS2 runtime.

Over in Git for Windows, we do rely on the ability to be able to pass empty values for environment variables, that's there is https://github.com/git-for-windows/msys2-runtime/commit/3e9c003101b17d11e250c8a3ec92de219db67860 in Git for Windows' fork of the MSYS2 runtime (and we've had it since 2015, the commit date of _that_ commit notwithstanding).

I am more than willing to contribute this patch to the MSYS2 project.

Now, I _could_ imagine that there are users who rely on the original behavior of the MSYS2 runtime. So maybe we need an "escape hatch", i.e. some magic keyword in the `MSYS` environment variable to turn the old behavior back on?

**Comment by dscho** [comment]
@eli-schwartz please download `install.zip` from https://github.com/msys2/msys2-runtime/actions/runs/2999371095#artifacts and extract `usr/bin/msys-2.0.dll`, replacing your existing copy, then test.

If it all works as you want it to, please leave a note at https://github.com/msys2/msys2-runtime/pull/101.

**Comment by eli-schwartz** [comment]
I would love to test this, but github has its ridiculous thing where you cannot download an artifact via the command line, and the redirection provided on the webpage is only valid for 60 seconds. I need to test this in a CI run, because I don't have Windows installed.

Fighting with github's malicious hatred of users is not the most effective use of my time. I'll settle for trusting you that it works.

If you'd like to verify this, then my failure is at https://github.com/mesonbuild/meson/runs/8181275151?check_suite_focus=true#step:6:1155 and my test case is https://github.com/eli-schwartz/meson/commit/afa38396052b3683c5b65a6ef09245f5fc0dce81

**Comment by dscho** [comment]
> I would love to test this

Here you go: 
[install.zip](https://github.com/msys2/msys2-runtime/files/9504539/install.zip)

**Comment by dscho** [comment]
@eli-schwartz ⬆️

**Comment by eli-schwartz** [comment]
I tried that, but got a couple hundred errors due to differing path semantics between `\\` and `/`. Not sure why it triggers here?

However, run_unittests.py::AllPlatformTests::test_run_target_files_path (the test that used to fail) now passes which I think is good? https://github.com/eli-schwartz/meson/runs/8240663819?check_suite_focus=true#step:7:385

**Comment by dscho** [comment]
> I tried that, but got a couple hundred errors due to differing path semantics between `\\` and `/`. Not sure why it triggers here?

Did you get those errors before, too, or are they new? Are they maybe due to v3.3.6, i.e. you see them happening after upgrading your regular MSYS2 runtime, too?

> However, run_unittests.py::AllPlatformTests::test_run_target_files_path (the test that used to fail) now passes which I think is good?

Yes, that is good. Let's get the PR over the finish line, then.

**Comment by dscho** [comment]
This has been pushed over the finish line.

**Comment by eli-schwartz** [comment]
Apparently those errors were indeed caused by the empty env vars fix...

Yes, those errors were new, and all I did to get them was to run the official msys2 setup GitHub action , install packages, and then replace the dll as suggested here. But I can't debug this well, since my only msys2 environment is running GitHub actions workflows. ;)

**Comment by lazka** [comment]
@eli-schwartz the errors you saw in CI were fixed by https://github.com/msys2-contrib/cpython-mingw/pull/107
